apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-read-only
  namespace: dale-fahad-super-secret-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
