apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-secret-access
  namespace: dale-fahad-super-secret-secrets
subjects:
  - kind: ServiceAccount
    name: deployer-sa
    namespace: dale-nick-fahad-nextjsapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-read-only
