apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-secret
spec:
  params:
    - name: secret-name
      description: name of the secret to copy
    - name: source-namespace
      description: namespace to get secrets from
    - name: target-namespace
      description: namespace for the deployment, to copy the secret to
  steps:
    - name: copy-secret
      image: quay.io/upslopeio/kubectl:latest
      script: |
        #!/bin/sh
        kubectl get secret $(params.secret-name) --namespace=$(params.source-namespace) -o yaml | sed 's/namespace: .*/namespace: $(params.target-namespace)/' | kubectl apply -f -
