apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcs-trigger-rb
subjects:
  - kind: ServiceAccount
    name: vcs-trigger-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vcs-trigger-role
