apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vcs-trigger-listener
spec:
  serviceAccountName: vcs-trigger-sa
  triggers:
    - interceptors:
        - github:
            secretRef:
              secretName: github-interceptor-secret
              secretKey: secretToken
      bindings:
        - ref: vcs-trigger-binding
      template:
        name: vcs-trigger-template
